In [1]:
import pandas as pd
file_path = "./실습데이터/ad_performance.csv"
df = pd.read_csv(file_path)
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

# 데이터 탐색
## 가. 통계로 요약하기
### 1. 요약(기술) 통계량 구하기
#### 가) 요약 통계량
  * 데이터 분포의 특징을 나타내는 통계량
  * 데이터 분석의 과정에서 데이터의 전체적인 특징과 분포를 빠르게 파악하기 위해 사용
  * 구현 방법 : df.describe()

In [2]:
df_stats = df.describe()
display(df_stats.round(1))

       Impressions  Clicks      Cost  Conversions    Revenue
count       5000.0  5000.0    5000.0       5000.0     5000.0
mean       12531.9   532.1  173572.5         24.5  1062507.4
std         4278.3   248.2   72085.7         13.7   544216.9
min         5001.0   100.0   50151.0          1.0   100440.0
25%         8769.5   323.0  112226.2         13.0   592358.2
50%        12625.5   534.0  172724.0         24.0  1078122.5
75%        16170.2   733.0  237086.2         36.0  1529310.5
max        19993.0   999.0  299992.0         49.0  1999273.0

#### 나) 숫자(Numeric) 데이터의 경우 (기본 동작)
  * count : 데이터 개수 (NaN 값 제외)
  * mean : 평균값
  * std : 표준편차 (데이터가 퍼져있는 정도)
  * min : 최솟값
  * 25% : 1사분위수 (하위 25% 지점의 값)
  * 50% : 중앙값 (median, 2사분위수)
  * 75% : 3사분위수 (하위 75% 지점의 값)
  * max : 최댓값

### 2. 요약 통계량으로부터 평균 구하기

In [3]:
avg_cost = df_stats.loc["mean", "Cost"]
print(f"{avg_cost:.1f}")
print("-" * 80)
avg_cost2 = df["Cost"].mean()
print(f"{avg_cost2:.1f}")

173572.5
--------------------------------------------------------------------------------
173572.5

### 3. 요약 통계량으로부터 최솟값, 최댓값 구하기

In [4]:
min_rev = df_stats.loc["min", "Revenue"]
max_rev = df_stats.loc["max", "Revenue"]
print(min_rev, max_rev)
print("-" * 80)
min_rev1, max_rev1 = min(df["Revenue"]), max(df["Revenue"])
print(min_rev1, max_rev1)

100440.0 1999273.0
--------------------------------------------------------------------------------
100440 1999273

### 4. 요약 통계량으로부터 분위수(quantile) 구하기

In [5]:
rev_25 = df_stats.loc["25%", "Revenue"]
rev_50 = df_stats.loc["50%", "Revenue"]
rev_75 = df_stats.loc["75%", "Revenue"]
print(rev_25, rev_50, rev_75)
print("-" * 80)
rev_25_1 = df["Revenue"].quantile(q=0.25)
rev_50_1 = df["Revenue"].quantile(q=0.5)
rev_75_1 = df["Revenue"].quantile(q=0.75)
print(rev_25_1, rev_50_1, rev_75_1)
print("-" * 80)
rev_50_2 = df["Revenue"].median()
print(rev_50_2)

592358.25 1078122.5 1529310.5
--------------------------------------------------------------------------------
592358.25 1078122.5 1529310.5
--------------------------------------------------------------------------------
1078122.5

### 5. 요약 통계량으로부터 표준편차(standard deviation) 구하기
#### 가) 표준편차 : 데이터들이 평균값에서 평균적으로 얼마나 떨어져 있는가?
  * 데이터의 '일관성' 또는 변동성을 보여주는 지표
  * 표준편차가 작다: 데이터들이 평균값 주변에 옹기종기 모여있다. (성과가 꾸준하고 예측 가능)
  * 표준편차가 크다: 데이터들이 평균값에서 멀리, 넓게 흩어져 있다. (성과가 들쭉날쭉하고 예측하기 힘듦)

In [6]:
std_rev = df_stats.loc["std", "Revenue"]
print(std_rev)
print("-" * 80)
std_rev1 = df["Revenue"].std()
print(std_rev1)

544216.869179562
--------------------------------------------------------------------------------
544216.869179562

In [7]:
count_rev = df_stats.loc["count", "Revenue"]
print(count_rev)
print("-" * 80)
count_rev1 = len(df["Revenue"])
print(count_rev1)
print("-" * 80)
count_rev2 = df["Revenue"].count()
print(count_rev2)

5000.0
--------------------------------------------------------------------------------
5000
--------------------------------------------------------------------------------
5000

## 나. 상관관계 분석(Correlation Analysis)
### 1. 개념 : 두 변수 사이에 연관성의 존재 여부와 연관성의 강도를 측정하여 분석하는 방법
### 2. 상관관계의 종류
#### 가) 양(+)의 상관관계
  * 한 변수의 값이 증가할 때 다른 변수의 값도 증가한다
  * 강도에 따라 강한 양의 상관관계, 약한 양의 상관관계가 있다
#### 나) 음(-)의 상관관계
  * 한 변수의 값이 증가할 때 다른 변수의 값은 감소한다
  * 강도에 따라 강한 음의 상관관계, 약한 음의 상관관계가 있다
#### 다) 상관계수(피어슨 상관계수) : 두 변수 갂에 존재하는 선형 관계의 정도를 수량화, +1 ~ -1
#### 라) 구현방법
  * df.corr(numeric_only=True) : 변수들 간의 상관 계수를 표현한 데이터프레임 생성 → 상관 행렬

In [8]:
df_correlation = df.corr(numeric_only = True)
display(df_correlation)

             Impressions    Clicks      Cost  Conversions   Revenue
Impressions     1.000000  0.104543  0.009052    -0.000656  0.011986
Clicks          0.104543  1.000000  0.001509     0.046552  0.015925
Cost            0.009052  0.001509  1.000000    -0.005274  0.009770
Conversions    -0.000656  0.046552 -0.005274     1.000000 -0.016981
Revenue         0.011986  0.015925  0.009770    -0.016981  1.000000