# 데이터 시각화
## 가. 탐색적 데이터 분석(EDA, Exploratory Data Analysis)
### 1. 개념: 시각화를 통한 데이터에 대한 이해(특징과 패턴 파악)
### 2. 시각화 (visualization)
#### 가) 데이터를 도표나 차트 등으로 정리하는 것
#### 나) 시각화를 통해 데이터의 특징을 쉽게 파악 할 수 있다
#### 다) 분석 결과를 상대방에게 효과적으로 전달 가능하다
### 3. python 시각화 라이브러리
#### 가) matplotlib
##### 1) Python에서 시각화 핛 수 있는 대표적인 라이브러리 
##### 2) import matplotlib.pyplot as plt
#### 나) seaborn
##### 1) matplotlib을 기반, 통계 데이터 시각화 라이브러리
##### 2) import seaborn as sns
#### 다) plotly
##### 1) 개념: 웹 브라우저 기반의 인터랙티브 시각화 라이브러리, 마우스 오버 시 데이터 값 표시(툴팁), 드래그를 통한 확대/축소, 범례 클릭을 통한 필터링 등 강력한 기능을 제공
##### 2) import plotly.express as px

In [2]:
import warnings
import pandas as pd
import plotly.express as px

warnings.filterwarnings("ignore")

file_path1 = "./실습데이터/tips.csv"
tips_df = pd.read_csv(file_path1)
display(tips_df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### 4. 주로 사용되는 시각화 도구
#### 가) 직선 그래프
##### 1) 개념: 두 개 이상의 데이터 포인트를 직선으로 연결하여 연속적인 변화와 추세를 시각적으로 표현하는 그래프
##### 2) px.line(data_frame, x, y, color)
##### 3) 하이퍼파라미터
  * data_frame : 데이터프레임
  * x, y : 시각화 할 컬럼
  * color : 새로운 변수를 추가하여 색상으로 구분

In [3]:
sort_by_bill = tips_df.sort_values(by = "total_bill")
fig1 = px.line(sort_by_bill, "total_bill", "tip", color="day")
fig1.write_html("./lines.html")
fig1.show()

#### 나) 막대 그래프
##### 1) 개념 : 범주형 컬럼에 대해 범주별 수치 데이터의 크기(총합, 평균 등)를 직사각형 막대로 표현하는 그래프
##### 2) 구현 방법
  * 수직 막대 : px.bar(data_frame, x, y)
  * 수평 막대: px.bar(data_frame, x, y, orientation='h')
##### 3) 하이퍼파라미터
  * data_frame : 데이터프레임
  * x, y
    * 수직형: x가 범주형 컬럼, y가 수치형 컬럼
    * 수평형: x가 수치형 컬럼, y가 범주형 컬럼
  * orientation: 'v' (수직, 기본값), 'h' (수평)

In [8]:
day_mean = tips_df.groupby(by="day")["total_bill"].mean()
df_day_mean = day_mean.reset_index()
df_day_mean = df_day_mean.rename(columns={"total_bill" : "avg_total_bill"})
fig2 = px.bar(df_day_mean, "day", "avg_total_bill", category_orders={"day" : ["Thur", "Fri", "Sat", "Sun"]}, color="day")
# fig3 = px.bar(df_day_mean, "avg_total_bill", "day", orientation = 'h', category_orders="day")
fig2.show()
# fig3.show()

#### 다) 원 그래프
##### 1) 개념 : 범주형 컬럼에서 전체에 대한 각 범주의 비율을 시각적으로 나타내며, 부분과 전체의 관계를 파악하기 용이한 그래프
##### 2) 구현 방법 : px.pie(data_frame, names, values, hole)
##### 3) 하이퍼파라미터
  * data_frame : 데이터프레임
  * names : 범주형 컬럼 (원의 조각 이름)
  * values : 수치형 컬럼 (조각의 크기)
  * hole : 0~1 사이 값을 설정하여 도넛 모양으로 변경

In [31]:
sex_ratio = tips_df["sex"].value_counts(normalize=True)
df_sex_ratio = sex_ratio.reset_index()
display(df_sex_ratio)
fig3 = px.pie(df_sex_ratio, names="sex", values="proportion", hole=0.5)
fig3.show()

      sex  proportion
0    Male    0.643443
1  Female    0.356557

In [34]:
day_ratio = tips_df["day"].value_counts(normalize=True)
df_day_ratio = day_ratio.reset_index()
display(df_day_ratio)
fig4 = px.pie(df_day_ratio, names="day", values="proportion", hole=0.6)
fig4.show()

    day  proportion
0   Sat    0.356557
1   Sun    0.311475
2  Thur    0.254098
3   Fri    0.077869

#### 라) 히스토그램
##### 1) 개념 : 수치형 데이터의 분포를 구간(bin)별로 나누어 구간별 누적 빈도를 직사각형의 막대로 표현하는 그래프
##### 2) 구현 방법
  * 수직형 : px.histogram(data_frame, x, y=None, nbins, color)
  * 수평형 : px.histogram(data_frame, x=None, y, color)
##### 3) 하이퍼파라미터
  * data_frame : 데이터프레임
  * x, y :
    * 수직형 : x가 수치형 컬럼, y=None
    * 수평형 : x =None, y가 수치형 컬럼
  * nbins : 빈(bin)의 개수 설정 (미지정 시 최적값 자동 계산)
  * color : 새로운 변수를 추가하여 색상으로 구분

In [47]:
fig5 = px.histogram(tips_df, x="total_bill", color="day", barmode='overlay', opacity=0.75)
fig5.update_traces(marker_line_color='black', marker_line_width=1)
fig5.show()
fig6 = px.histogram(tips_df, x="total_bill", color="day", barmode='group')
fig6.show()

#### 마) 박스 플롯
##### 1) 개념: 수치형 컬럼에 대해서 최소값(min), 1사분위수(Q1), 2사분위수(Q2, median), 3사분위수(Q3), 최대값(max)을 이용하여 데이터의 분포를 시각적으로 요약하고 이상치를 식별하는데 유용한 그래프
##### 2) 구현 방법 : px.box(data_frame, x, y, color)
##### 3) 하이퍼파라미터
  * data_frame : 데이터프레임
  * x, y :
    * 수직형 : x가 범주형 컬럼, y가 수치형 컬럼
    * 수평형 : x가 수치형 컬럼, y가 범주형 컬럼
  * color : 새로운 변수를 추가하여 색상으로 구분

In [60]:
fig7 = px.box(tips_df, "day", "tip", color="time", category_orders={"day" : ["Thur", "Fri", "Sat", "Sun"]})
fig7.show()
fig8 = px.box(tips_df, "tip", "time", color="sex")
fig8.show()

#### 바) 산점도
##### 1)  개념 : 두 변수의 상관 관계를 직교 좌표계의 평면에 점으로 표현하는 그래프
##### 2)  구현 방법 : px.scatter(data_frame, x, y, color)
##### 3) 하이퍼파라미터
  * data_frame : 데이터프레임
  * x, y : 상관 관계를 분석한 두 수치형 컬럼
  * color : 그룹별 색상 구분

In [53]:
fig9 = px.scatter(tips_df, "total_bill", "tip", color = "day")
fig9.show()

#### 사) 히트맵
##### 1) 개념: 변수들 간의 상관 계수 크기를 색상의 농도로 표현하여 변수 간의 관계를 한눈에 파악하는 그래프
##### 2) 구현 방법: px.imshow(data_frame, text_auto, color_continuous_scale)
##### 3)  하이퍼파라미터
  * data_frame : 상관 행렬(데이터프레임)
  * text_auto : 상관계수 수치 형식을 표시 (text_auto='.2f')
  * color_continuous_scale: 히트맵의 색상 테마 설정 (예: 'RdBu_r', 'Viridis')

In [61]:
corr_matrix = tips_df.corr(numeric_only = True)
display(corr_matrix)
fig10 = px.imshow(corr_matrix, text_auto=".2f", color_continuous_scale = 'RdBu')
fig10.show()

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000