# weather.csv를 이용한 데이터 탐색

## 데이터 불러오기

In [2]:
import pandas as pd
file_path = "./실습데이터/weather.csv"
df = pd.read_csv(file_path)
display(df)

       temp  hum   atm  speed
0        17   34  1018    3.1
1        17   34  1018    3.1
2        17   34  1018    3.1
3        17   34  1018    3.1
4        17   34  1018    3.1
...     ...  ...   ...    ...
99995     9   71  1009    2.6
99996     9   71  1009    2.6
99997     9   71  1009    2.6
99998     9   71  1009    2.6
99999     9   71  1009    2.6

[100000 rows x 4 columns]

## 요약 통계량 구하기

In [3]:
df_stats = df.describe()
display(df_stats)

                temp            hum            atm          speed
count  100000.000000  100000.000000  100000.000000  100000.000000
mean       16.909460      78.159290    1005.071590       3.315666
std         3.840548      21.021064       5.657643       1.915367
min         9.000000      17.000000     993.000000       0.500000
25%        15.000000      66.000000    1002.000000       1.500000
50%        16.000000      87.000000    1006.000000       3.100000
75%        19.000000      93.000000    1007.000000       4.600000
max        27.000000     100.000000    1028.000000      10.300000

## temp 컬럼에 대한 평균값 구하기

In [4]:
avg_temp = df_stats.loc["mean", "temp"]
print(avg_temp)

16.90946

## hum 컬럼에 대한 최소값 구하기

In [5]:
min_hum = df_stats.loc["min", "hum"]
print(min_hum)

17.0

## hum 컬럼에 대한 최대값 구하기

In [6]:
max_hum = df_stats.loc["max", "hum"]
print(max_hum)

100.0

## atm 컬럼에 대한 중간값 구하기

In [7]:
med_atm = df_stats.loc["50%", "atm"]
print(med_atm)

1006.0

## speed 컬럼에 대한 표준 편차 구하기

In [8]:
std_speed = df_stats.loc["std", "speed"]
print(std_speed)

1.9153671874496094

## 상관 분석

In [9]:
# 상관 행렬 구하기
corr_matrix = df.corr()
display(corr_matrix)

           temp       hum       atm     speed
temp   1.000000 -0.461839  0.179666 -0.069841
hum   -0.461839  1.000000 -0.498329 -0.179915
atm    0.179666 -0.498329  1.000000 -0.330514
speed -0.069841 -0.179915 -0.330514  1.000000

In [13]:
# 온도(temp) 컬럼과 습도(hum) 컬럼의 상관 관계 분석
print(corr_matrix.loc["temp", "hum"])

-0.46183883572635326