# 환경 설정

In [1]:
# 필요한 라이브러리 / 모듈 / 클래스 / 함수 임포트
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import root_mean_squared_error
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# 데이터 불러오기

In [2]:
# 파일 경로 설정
file_path='./데이터/house_price.csv'

# DataFrame 생성
df = pd.read_csv(file_path)

# 결과 확인
display(df)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

# 학습용과 평가용 데이터 생성

In [3]:
# 75:25의 비율로 학습용과 평가용 데이터 생성

## X_data 생성: 정답 레이블 제거
X_data = df.drop(columns=['medv'])
display(X_data)

print('-'*80)

## y_data 생성: 정답 레이블 인덱싱
y_data = df['medv']
print(y_data)

## train_test_split() 함수 호출
X_train, X_test, y_train, y_test = train_test_split(
    X_data,
    y_data,
    test_size=0.25,
    random_state=0
)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

--------------------------------------------------------------------------------
0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [4]:
# 학습용 데이터 확인: 인덱스 확인
print(f'X_train의 인덱스: \n{X_train.index}')
print('-'*80)
print(f'y_train의 인덱스: \n{y_train.index}')

X_train의 인덱스:
Index([245,  59, 276, 395, 416, 491, 170, 419,  55, 235,
       ...
       211,   9, 359, 195, 251, 323, 192, 117,  47, 172],
      dtype='int64', length=379)
--------------------------------------------------------------------------------
y_train의 인덱스:
Index([245,  59, 276, 395, 416, 491, 170, 419,  55, 235,
       ...
       211,   9, 359, 195, 251, 323, 192, 117,  47, 172],
      dtype='int64', length=379)

# 전처리: 표준화

In [5]:
# 표준화 도구 생성
scaler = StandardScaler()

In [6]:
# 학습용과 평가용 데이터 변환: 학습용 기준(평균, 표준편차)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 변환의 결과 확인: pandas 자료형(DataFrame) -> 넘파이 배열
print(X_train_scaled)
print('-'*80)
print(X_test_scaled)

[[-0.3906002   0.42637011 -0.74491444 ...  0.27878885  0.34049624
   0.82212111]
 [-0.40127639  0.5525335  -0.84901832 ...  0.55287698  0.42774893
  -0.46241699]
 [-0.40110543  1.18335044 -0.66648002 ... -0.40643148  0.34184377
  -0.90310809]
 ...
 [-0.3954927  -0.49882807 -0.15309105 ... -0.31506877  0.40091059
  -0.31227617]
 [-0.38599992 -0.49882807 -0.59517599 ... -0.26938741  0.38103449
   0.86938766]
 [-0.39692832 -0.49882807 -1.003035   ... -0.86324503  0.42774893
   0.29801844]]
--------------------------------------------------------------------------------
[[-0.4056463  -0.49882807 -1.11854752 ... -0.72620097  0.18418254
  -0.72377323]
 [ 0.7056307  -0.49882807  1.00060803 ...  0.78128376  0.08244389
  -0.41932101]
 [-0.39994626 -0.49882807  0.40022816 ... -0.95460774  0.39226392
  -0.28447232]
 ...
 [-0.37143398 -0.49882807 -0.16877794 ... -0.04098064  0.42033751
  -0.35815253]
 [-0.40185719 -0.49882807  2.07729878 ...  0.27878885  0.23100928
   0.69978415]
 [-0.40470175  0.8889692  -1.26971205 ... -0.04098064  0.42774893
  -0.84471999]]

In [7]:
# Pytorch Tensor 변환 및 디바이스로 이동
"""
# 넘파이 배열 -> pytorch 학습에 적합한 형태의 자료형(Tensor)으로 변환
"""
X_train_tensor = torch.FloatTensor(X_train_scaled)
X_test_tensor = torch.FloatTensor(X_test_scaled)
y_train_tensor = torch.FloatTensor(y_train.values)

In [8]:
# pytorch용 표준 데이터셋 생성 -> 미니 배치 생성 준비 단계
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)

In [9]:
# DataLoader 생성

"""
# 학습용 데이터: 379개 -> batch_size=16 -> 미니 배치:24개 -> 미니 배치 단위 학습 가능
"""

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

# MLP 회귀 모델 생성

In [10]:
# 입력 특성(컬럼) 수 추출
input_dim = X_train_tensor.shape[1]
print(f'입력 데이터 특성의 수: {input_dim}')

print('-'*80)

# nn.Sequential 클래스 사용: 입력층 -> 은닉층1 -> 은닉층2 -> 출력층 구성
model = nn.Sequential(
    nn.Linear(input_dim, 64), # [입력층 -> 은닉층1]: 입력 13개, 인공 뉴런 64개로 구성
    nn.ReLU(),                # [활성화 함수]: 비선형 연산(음수 -> 0)
    nn.Linear(64, 32),        # [은닉층2]: 입력 64, 인공 뉴런 32개로 구성
    nn.ReLU(),                # [활성화 함수]: 비선형 연산(음수 -> 0)
    nn.Linear(32, 1)          # [출력층]: 입력 32, 출력 뉴런 1개로 구성 -> 주택 가격(예측)
)

print(f'생성된 모델 아키텍처: \n{model}')

입력 데이터 특성의 수: 13
--------------------------------------------------------------------------------
생성된 모델 아키텍처:
Sequential(
  (0): Linear(in_features=13, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=1, bias=True)
)

# 손실 함수 설정

In [11]:
# 회귀 문제의 손실 함수: 평균 제곱 오차(MSE)
criterion = nn.MSELoss()

# 최적화 알고리즘 설정

In [12]:
# 최적화: Adam 적용(SGD 개선)
optimizer = optim.Adam(model.parameters(), lr=0.005)

# 모델 학습

In [13]:
# 학습 횟수 설정
epochs = 200

# 모델을 학습 모드로 전환
model.train()

# for 반복문 이용 학습 진행
for epoch in range(epochs):

    ## 손실값 초기화
    epoch_loss = 0.0

    for batch_x, batch_y in train_loader:
        # 1) 기울기 초기화(이전 학습의 결과물 삭제)
        optimizer.zero_grad()

        # 2) 순전파 연산 (출력층 뉴런 입력의 총합 -> 예측값)
        predictions = model(batch_x)

        # 3) 손실 계산 (batch_y를 (batch_size, 1) 모양으로 맞춰줌)
        loss = criterion(predictions, batch_y.unsqueeze(1))

        # 4) 오차역전파 (가중치별 기울기 산출)
        loss.backward()

        # 5) 가중치 매개변수 갱신
        optimizer.step()

        # 손실값 업데이트: pytorch Tensor 자료형 파이썬 숫자형으로 변환
        epoch_loss += loss.item()

    if (epoch + 1) % 20 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Train MSE Loss: {epoch_loss/len(train_loader):.4f}")

Epoch [20/200], Train MSE Loss: 7.3108
Epoch [40/200], Train MSE Loss: 5.5490
Epoch [60/200], Train MSE Loss: 4.4283
Epoch [80/200], Train MSE Loss: 4.5430
Epoch [100/200], Train MSE Loss: 3.3228
Epoch [120/200], Train MSE Loss: 3.0963
Epoch [140/200], Train MSE Loss: 3.4171
Epoch [160/200], Train MSE Loss: 3.1569
Epoch [180/200], Train MSE Loss: 2.7930
Epoch [200/200], Train MSE Loss: 2.3872

# 모델 평가

In [14]:
# 모델을 평가 모드로 전환
model.eval()

# 평가용 데이터를 이용한 예측: 평가 시에는 기울기 계산 비활성화
with torch.no_grad():
    # 출력 뉴런의 입력 신호의 총합(예측값) 도출
    test_preds = model(X_test_tensor).cpu().numpy()

# 성능 평가: rmse 계산
rmse_mlp = root_mean_squared_error(y_test, test_preds)

# 결과 확인
print(f"[보스톤 주택 가격 예측] PyTorch MLP 평가 RMSE: {rmse_mlp:.4f}")

[보스톤 주택 가격 예측] PyTorch MLP 평가 RMSE: 4.1717