# 탐색적 데이터 분석(EDA) : 당뇨병 건강 지표 분석

In [1]:
import pandas as pd
import plotly.express as px

## 데이터 불러오기

In [2]:
file_path = "./실습데이터/diabetes_binary_5050split_health_indicators_BRFSS2015.csv"
df = pd.read_csv(file_path)
display(df.head())

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

## 1. 정답 레이블(당뇨병 여부) 분포 분석

In [53]:
diabates_ratio = df["Diabetes_binary"].value_counts(normalize=True)
df1 = diabates_ratio.reset_index()
df1 = df1.replace({0.0 : "정상", 1.0 : "당뇨"})

fig1 = px.pie(df1, names="Diabetes_binary", values="proportion")
fig1.show()

## 2. 당뇨병과 고혈압의 관계 분석

In [ ]:
highbp = df.groupby(by="HighBP")["Diabetes_binary"].count()
df2 = highbp.reset_index()
df2 = df2.replace({0.0 : "정상", 1.0 : "고혈압"})

fig2 = px.bar(df2, x = "HighBP", y = "Diabetes_binary", color="HighBP")
fig2.show()

## 3. 당뇨병과 고지혈증의 관계 분석

In [ ]:
highchol = df.groupby(by="HighChol")["Diabetes_binary"].count()
df3 = highchol.reset_index()

fig3 = px.his(df3, x = "HighChol", y = "Diabetes_binary", text_auto=True)
fig3.show()

## 4. 당뇨병과 BMI(비만)의 관계 분석

In [62]:
bmi = df.groupby(by="BMI")["Diabetes_binary"].count()
df4 = bmi.reset_index()

fig4 = px.histogram(df4, x = "BMI", y = "Diabetes_binary")
fig4.update_traces(marker_line_color='black', marker_line_width=1)
fig4.show()

## 5. 당뇨병과 흡연의 관계 분석

In [39]:
smoke = df.groupby(by="Smoker")["Diabetes_binary"].count()
df5 = smoke.reset_index()

fig5 = px.bar(df5, x = "Smoker", y = "Diabetes_binary")
fig5.show()

## 6. 당뇨병과 성별의 관계 분석

In [ ]:
sex = df.groupby(by="Sex")["Diabetes_binary"].count()
df6 = sex.reset_index()
df6 = df6.replace({0.0 : "female", 1.0 : "male"})
display(df6)

fig6 = px.pie(df6, names = "Sex", values = "Diabetes_binary")
fig6.show()

      Sex  Diabetes_binary
0  female            38386
1    male            32306

## 7. 당뇨병과 나이의 관계 분석

In [58]:
age = df.groupby(by="Age")["Diabetes_binary"].count()
df6 = age.reset_index()

fig6 = px.histogram(df6, x = "Age", y = "Diabetes_binary", nbins = 13)
fig6.show()

## 8. 당뇨병과 교육 수준의 관계 분석

In [61]:
education = df.groupby(by="Education")["Diabetes_binary"].count()
df8 = education .reset_index()

fig8 = px.bar(df8, x = "Education", y = "Diabetes_binary")
fig8.show()