# 데이터전처리
## 가. 개요
### 1. 개념 : 수집한 데이터를 분석 및 머신러닝 모델 학습에 적합한 형태로 변환하는 작업
### 2. 목적 : 데이터 내 노이즈 및 불균형을 정제하여 모델 학습의 안정성과 예측 성능 향상
## 나. 특성 공학 (Feature Engineering) 및 주요 전처리 기법
### 1. 파생 변수 생성 : 기존 변수들을 조합하거나 가공하여 유의미한 새 변수 생성
### 2. 범주형 변수 변환 (Encoding) :

In [2]:
import pandas as pd
import numpy as np

file_path1 = "./실습데이터/iris_dataset.csv"
df1 = pd.read_csv(file_path1)
display(df1)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

#### 가) 원-핫 인코딩 (One-Hot Encoding) : 범주별로 고유 컬럼을 생성해 0과 1로 표현 (pd.get_dummies())

In [ ]:
print(df1['label'].value_counts())
df_encoded1 = pd.get_dummies(df1, columns=['label'], dtype=int)
display(df_encoded1)

label
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label_setosa,label_versicolor,label_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

#### 나) 레이블 인코딩 (Label Encoding) : 범주형 데이터를 0부터 $n-1$까지의 정수 수치로 변환 (df.replace())

In [8]:
df_encoded2 = df1.replace({'setosa' : 0, 'versicolor' : 1, 'virginica' : 2})
display(df_encoded2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

### 3. 연속형 변수 변환 (Scaling) :
#### 가) 정규화 (Normalization): 데이터의 최소-최대 범위를 [0, 1] 사이 값으로 변환 ($x_{new} = \frac{x-x_{min}}{x_{max}-x_{min}}$)

In [54]:
# 데이터 생성
data1 = {
    "age" : [22, 25, 47, 38, 29],
    "income" : [3000, 3500, 8500, 6000, 4200]
}

df2 = pd.DataFrame(data1)

display(df2)

   age  income
0   22    3000
1   25    3500
2   47    8500
3   38    6000
4   29    4200

In [ ]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()

data_minmax = minmax_scaler.fit_transform(df2)
data_index = df2.index

df2_nomalized = pd.DataFrame(data = data_minmax, index = data_index, columns = ['nomalized_age', 'nomalized_income'])

display(df2_nomalized)

   nomalized_age  nomalized_income
0           0.00          0.000000
1           0.12          0.090909
2           1.00          1.000000
3           0.64          0.545455
4           0.28          0.218182

#### 나) 표준화 (Standardization) : 평균 0, 표준편차 1인 정규분포 형태로 변환 ($x_{new} = \frac{x-\mu}{\sigma}$)

In [22]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

data_standard = standard_scaler.fit_transform(df2)

df2_standard = pd.DataFrame(data = data_standard, index = data_index, columns = ['standard_age', 'standard_income'])

display(df2_standard)

   standard_age  standard_income
0     -1.114505        -1.016651
1     -0.786709        -0.767472
2      1.617124         1.724319
3      0.633738         0.478424
4     -0.349648        -0.418621

#### 다) 머신러닝 알고리즘별 Scaling 가이드

| 알고리즘 분류 | 대표 모델 | 추천 전처리 방법 | 핵심 이유 |
| :--- | :--- | :--- | :--- |
| **선형 & 규제 모델** | Linear / Logistic Regression, Ridge, Lasso | `StandardScaler` | L1/L2 규제 패널티 계산 시 스케일 영향 차단 |
| **SVM & 차원 축소** | SVM, PCA, LDA | `StandardScaler` | 초평면 마진 및 분산 최적화 영향 최소화 |
| **딥러닝 (신경망)** | MLP, CNN, RNN 등 | `StandardScaler` 또는<br>(이상치 clip 후) `MinMaxScaler` | 스케일러 1개만 적용 (경사하강법 수렴 속도 최적화) |
| **거리 기반 모델** | K-Means 등 | 이상치 clip 후<br>`StandardScaler` 또는 `RobustScaler` | K-Means는 이상치에 극도로 취약 |
| **트리 기반 모델** | Decision Tree, Random Forest, XGBoost, LightGBM 등 | **스케일링 불필요** | 변수의 크기가 아닌 대소 비교를 통한 조건 분할 방식 사용 |

### 3. 구간화 (Binning) : 연속형 수치 데이터를 일정 기준 구간으로 나누어 범주형 데이터로 변환 (pd.cut())

In [ ]:
df2_binned = pd.cut(df2["age"], bins = [0, 10, 20, 30, 40, 50, 60, 70], labels = ['0s', "10s", "20s", "30s", '40s', '50s', '60s'])
display(df2_binned)

0    20s
1    20s
2    40s
3    30s
4    20s
Name: age, dtype: category
Categories (7, str): ['0s' < '10s' < '20s' < '30s' < '40s' < '50s' < '60s']

In [55]:
data2 = {'age':[1, 10, 15, 13, 21, 23, 37, 31, 43, 80, 61, 20, 41, 32, 100],
        'gender':['male','male','female','female','female','male','male','female','female','female','male','male','female','female','female']}

df3 = pd.DataFrame(data2)
display(df3)

    age  gender
0     1    male
1    10    male
2    15  female
3    13  female
4    21  female
5    23    male
6    37    male
7    31  female
8    43  female
9    80  female
10   61    male
11   20    male
12   41  female
13   32  female
14  100  female

In [43]:
binned_age = pd.cut(
    df3["age"],
    bins = [0, 9, 19, 29, 39, 49, 59, 69, 79, 89, 99, 200],
    labels = ['0s', "10s", "20s", "30s", '40s', '50s', '60s', '70s', '80s', '90s', '100+']
)

df3_binned = df3['binned_age'] = binned_age

display(df3)

    age  gender binned_age
0     1    male         0s
1    10    male        10s
2    15  female        10s
3    13  female        10s
4    21  female        20s
5    23    male        20s
6    37    male        30s
7    31  female        30s
8    43  female        40s
9    80  female        80s
10   61    male        60s
11   20    male        20s
12   41  female        40s
13   32  female        30s
14  100  female       100+

## 다. 주요 판다스(Pandas) 전처리 함수
### 1. pd.DataFrame.query(): 문자열 조건식을 활용한 직관적 행 필터링

In [ ]:
df1_queried1 = df1.query('label == "virginica"')
display(df1_queried1)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
100,6.3,3.3,6.0,2.5,virginica
101,5.8,2.7,5.1,1.9,virginica
102,7.1,3.0,5.9,2.1,virginica
103,6.3,2.9,5.6,1.8,virginica
104,6.5,3.0,5.8,2.2,virginica
105,7.6,3.0,6.6,2.1,virginica
106,4.9,2.5,4.5,1.7,virginica
107,7.3,2.9,6.3,1.8,virginica
108,6.7,2.5,5.8,1.8,virginica
109,7.2,3.6,6.1,2.5,virginica
110,6.5,3.2,5.1,2.0,virginica
111,6.4,2.7,5.3,1.9,virginica
112,6.8,3.0,5.5,2.1,virginica
113,5.7,2.5,5.0,2.0,virginica
114,5.8,2.8,5.1,2.4,virginica
115,6.4,3.2,5.3,2.3,virginica
116,6.5,3.0,5.5,1.8,virginica
117,7.7,3.8,6.7,2.2,virginica
118,7.7,2.6,6.9,2.3,virginica
119,6.0,2.2,5.0,1.5,virginica
120,6.9,3.2,5.7,2.3,virginica
121,5.6,2.8,4.9,2.0,virginica
122,7.7,2.8,6.7,2.0,virginica
123,6.3,2.7,4.9,1.8,virginica
124,6.7,3.3,5.7,2.1,virginica
125,7.2,3.2,6.0,1.8,virginica
126,6.2,2.8,4.8,1.8,virginica
127,6.1,3.0,4.9,1.8,virginica
128,6.4,2.8,5.6,2.1,virginica
129,7.2,3.0,5.8,1.6,virginica
130,7.4,2.8,6.1,1.9,virginica
131,7.9,3.8,6.4,2.0,virginica
132,6.4,2.8,5.6,2.2,virginica
133,6.3,2.8,5.1,1.5,virginica
134,6.1,2.6,5.6,1.4,virginica
135,7.7,3.0,6.1,2.3,virginica
136,6.3,3.4,5.6,2.4,virginica
137,6.4,3.1,5.5,1.8,virginica
138,6.0,3.0,4.8,1.8,virginica
139,6.9,3.1,5.4,2.1,virginica
140,6.7,3.1,5.6,2.4,virginica
141,6.9,3.1,5.1,2.3,virginica
142,5.8,2.7,5.1,1.9,virginica
143,6.8,3.2,5.9,2.3,virginica
144,6.7,3.3,5.7,2.5,virginica
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [52]:
df1_queried2 = df1.query('`petal length (cm)` <= 1.2')
display(df1_queried2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
13,4.3,3.0,1.1,0.1,setosa
14,5.8,4.0,1.2,0.2,setosa
22,4.6,3.6,1.0,0.2,setosa
35,5.0,3.2,1.2,0.2,setosa

In [56]:
data3 = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 22, 28],
    'Salary': [5000, 7000, 4500, 8000, 6000],
    'Dept': ['HR', 'IT', 'HR', 'IT', 'Marketing']
} 

df4 = pd.DataFrame(data3)

display(df4)

      Name  Age  Salary       Dept
0    Alice   25    5000         HR
1      Bob   30    7000         IT
2  Charlie   35    4500         HR
3    David   22    8000         IT
4      Eva   28    6000  Marketing

In [60]:
df4_queried1 = df4.query('`Age` >= 25 & Salary >= 6000')
display(df4_queried1)

  Name  Age  Salary       Dept
1  Bob   30    7000         IT
4  Eva   28    6000  Marketing

In [63]:
file_path2 = "./실습데이터/ad_performance.csv"

df5 = pd.read_csv(file_path2)

display(df5)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

In [64]:
df5_queried1 = df5.query("`Channel` == 'Facebook'")

display(df5_queried1)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516
6,2025-01-01,Facebook,30s,Female,14083,155,79464,1,424394
8,2025-01-01,Facebook,20s,Female,15249,176,184655,1,271550
9,2025-01-01,Facebook,20s,Male,6518,651,57393,27,139854
...,...,...,...,...,...,...,...,...,...
4981,2025-06-29,Facebook,50s+,Male,11579,546,100479,34,1181886
4984,2025-06-29,Facebook,50s+,Male,8890,749,267827,37,757074
4986,2025-06-29,Facebook,40s,Male,14067,727,102370,45,296552
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504
4994,2025-06-29,Facebook,30s,Male,12482,429,250816,47,330298

In [65]:
df5_queried2 = df5.query("`Revenue` >= 1500000")

display(df5_queried2)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516
7,2025-01-01,Google,40s,Male,14872,431,221715,17,1677619
...,...,...,...,...,...,...,...,...,...
4985,2025-06-29,Google,50s+,Male,8463,846,219915,9,1987591
4987,2025-06-29,Naver,50s+,Female,13989,674,226994,17,1842078
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504
4991,2025-06-29,Naver,20s,Female,8196,563,106645,36,1588784
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754

In [ ]:
df5_queried3 = df5.query("`Revenue` >= 1500000 & `Channel` == 'Google'")

display(df5_queried3)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
7,2025-01-01,Google,40s,Male,14872,431,221715,17,1677619
12,2025-01-01,Google,50s+,Female,14972,301,50832,19,1654250
13,2025-01-01,Google,40s,Female,16131,802,53791,35,1727164
18,2025-01-01,Google,40s,Female,11685,287,139501,15,1777642
...,...,...,...,...,...,...,...,...,...
4938,2025-06-27,Google,50s+,Female,14760,487,276979,18,1795600
4944,2025-06-27,Google,20s,Female,11164,823,113620,21,1924905
4979,2025-06-29,Google,20s,Female,17176,834,194693,47,1579548
4985,2025-06-29,Google,50s+,Male,8463,846,219915,9,1987591
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754

### 2. 데이터 병합 (Concat) : pd.concat()
#### 가) 개념 및 특징
- 여러 데이터프레임(DataFrame)이나 시리즈(Series)를 축(axis)을 기준으로 연결하여 하나의 데이터프레임으로 병합하는 함수
- 기본값(`axis=0`)은 **행 방향(위아래)**으로 병합하며, 공통된 컬럼을 기준으로 데이터를 쌓음
- `axis=1` 지정 시 **열 방향(좌우)**으로 병합
- `ignore_index=True` 옵션을 설정하면 기존 인덱스를 무시하고 `0`부터 시작하는 새로운 인덱스를 재할당

In [3]:
# 샘플 데이터프레임 생성
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']})
df3 = pd.DataFrame({'A': ['A4', 'A5'], 'B': ['B4', 'B5']})

# axis=0 방향으로 병합 (기본값, 위아래 병합)
# ignore_index=True를 통해 인덱스를 0, 1, 2, 3, 4, 5로 재배열
df_concat = pd.concat([df1, df2, df3], ignore_index=True)

display(df_concat)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
5  A5  B5